import {CATEGORIES,validateNote,searchNotes,notesInCategory,updatedNote} from './core.mjs';
const DB='mom-notes-v1',STORE='notes';let notes=[],currentCategory='film',editing=null,existingFile=null,deleted=null;
const $=s=>document.querySelector(s);function toast(t,undo=false){const el=$('#toast');el.innerHTML='';el.append(document.createTextNode(t));if(undo){const b=document.createElement('button');b.textContent=' 撤销';b.onclick=undoDelete;el.append(b)}el.classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.add('hidden'),5000)}
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function tx(mode,fn){const db=await openDB();return new Promise((ok,no)=>{const t=db.transaction(STORE,mode),s=t.objectStore(STORE);fn(s);t.oncomplete=()=>{db.close();ok()};t.onerror=()=>no(t.error)})}
async function load(){const db=await openDB();notes=await new Promise((ok,no)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});db.close();renderCategories()}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));scrollTo(0,0)}
document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g)show(g.dataset.go)});
function renderCategories(){const root=$('#categories');root.innerHTML='';for(const [key,[icon,title,desc]] of Object.entries(CATEGORIES)){const b=document.createElement('button');b.className='card cat';b.innerHTML=`<span class="emoji">${icon}</span><b>${title}</b><span>${desc}</span><span class="count">${notesInCategory(notes,key).length} 条</span>`;b.onclick=()=>openCategory(key);root.append(b)}}
function openCategory(key){currentCategory=key;$('#listTitle').textContent=CATEGORIES[key][1];$('#listDesc').textContent=CATEGORIES[key][2];renderList(notesInCategory(notes,key));show('list')}
function renderList(items,root=$('#noteList')){root.innerHTML='';if(!items.length){root.innerHTML='<div class="empty">这里还没有备忘。点下面按钮记一条吧。</div>';return}items.forEach(n=>{const b=document.createElement('button');b.className='note';const attach=n.file?`<span>📎 ${escapeText(n.file.name)}</span>`:'';b.innerHTML=`<b>${escapeText(n.title||'无标题')}</b><span>${escapeText(n.body||'')}</span>${attach}`;b.onclick=()=>openEditor(n);root.append(b)})}
function escapeText(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function resetEditor(category=currentCategory){editing=null;existingFile=null;$('#editorTitle').textContent='新备忘';$('#category').value=category;$('#noteTitle').value='';$('#body').value='';$('#attachment').value='';$('#fileMeta').textContent='';$('#editActions').classList.add('hidden');show('editor')}
function openEditor(n){editing=n;existingFile=n.file||null;$('#editorTitle').textContent='查看和修改备忘';$('#category').value=n.category;$('#noteTitle').value=n.title;$('#body').value=n.body;$('#attachment').value='';$('#fileMeta').textContent=n.file?`已有文件：${n.file.name}（选择新文件可替换）`:'';$('#editActions').classList.remove('hidden');show('editor')}
for(const [key,v] of Object.entries(CATEGORIES)){const o=document.createElement('option');o.value=key;o.textContent=v[1];$('#category').append(o)}
$('#newNote').onclick=()=>resetEditor('film');$('#newInCategory').onclick=()=>resetEditor(currentCategory);$('#editorBack').onclick=()=>editing?openCategory(editing.category):show('notes');
$('#attachment').onchange=e=>{$('#fileMeta').textContent=e.target.files[0]?`已选择：${e.target.files[0].name}`:''};
$('#noteForm').onsubmit=async e=>{e.preventDefault();const f=$('#attachment').files[0];const patch={category:$('#category').value,title:$('#noteTitle').value.trim(),body:$('#body').value.trim(),file:f?{name:f.name,type:f.type,size:f.size,blob:f}:existingFile};if(!validateNote(patch).ok){toast('请写标题或内容');return}const n=editing?updatedNote(editing,patch):{...patch,id:crypto.randomUUID(),createdAt:Date.now(),updatedAt:Date.now()};await tx('readwrite',s=>s.put(n));notes=notes.filter(x=>x.id!==n.id).concat(n);currentCategory=n.category;renderCategories();openCategory(n.category);toast('已保存在这台设备上')};
$('#deleteNote').onclick=async()=>{if(!editing||!confirm('确定删除这条备忘吗？删除后 5 秒内可以撤销。'))return;deleted=editing;await tx('readwrite',s=>s.delete(editing.id));notes=notes.filter(n=>n.id!==editing.id);renderCategories();openCategory(editing.category);toast('已删除',true)};
async function undoDelete(){if(!deleted)return;await tx('readwrite',s=>s.put(deleted));notes.push(deleted);const c=deleted.category;deleted=null;renderCategories();openCategory(c);toast('已撤销删除')}
$('#searchForm').onsubmit=e=>{e.preventDefault();const q=$('#search').value;const found=searchNotes(notes,q),root=$('#searchResults');root.innerHTML=q.trim()?`<h3>搜索结果 · ${found.length} 条</h3>`:'';if(q.trim())renderList(found,root);};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});load().catch(()=>toast('浏览器存储不可用，请关闭无痕模式后重试'));
